### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by RostakaGmfun**
The Linux build on rend2 branch was apparently broken.
This PR fixes this (tested with gcc-4.9).

Please verify builds on other platforms, if possible.

### CODE REVIEW

**Comment by RostakaGmfun** [comment]
Anybody there?

**Comment by xycaleth** [comment]
Sorry I haven't been able to test out the changes yet. However, I don't agree with all the changes that have been made. I'll comment on them now

**Comment by RostakaGmfun** [comment]
Fixed some comments.
Regarding the `offsetof` issue:

g++-4.9 gives this kind of error: the value of ‘surfInfo’ is not usable in a constant expression.
However, if i replace the offseotf with this kind of stuff:

(size_t)(&((mdxmSurfHierarchy_t*)(nullptr))->childIndexes[surfInfo->numChildren])
it compiles well.

But it seems like gcc uses __builtin_offsetof here, and that function does not accept non-constant expressions.

To be honest, I don't like the sizeof() approach much, however dereferencing nullptr is not quite a good idea as well.

I will be happy if anybody could propose more elegant solution :)

**Comment by xycaleth** [comment]
No longer needed - this build fix has been superseded by #60

**Pull request closed without merging**
